#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Aug  4 19:09:56 2025

@author: michalis
"""

INI_CATS = ['EMS','SIMBAD-LBVs','deBURGOS+24','WESMAYER+22','SEARLE+08','McERLEAN+99','CROWTHER+06','FIRNSTEIN+12', 'FRASER+10', 'HAUCKE+19','SIMBAD-BSGs']
cm.sort(['STAR'])
LOC = [('MW' in x) or ('LMC' in x) or ('SMC' in x) for x in cm['GAL']]
cm = cm[LOC]
cm = cm[(cm['MK']<-2.5)]
cm = cm[:100]  #4/8 15:30
cm = cm[100:500]  #4/8 15:42
cm = cm[500:1000]  #5/8 11:00
cm = cm[1000:1500]  #5/8 14:00
cm = cm[1500:1935]  #5/8 19:00
cm = cm[1935:]  #6/8 08:00
total ~2200 stars



